### ISSUE TITLE
(Not issue) 

### ISSUE THREAD

**Issue by ORGaniZMo** [monero-ecosystem/vanity-monero#5]
Any ideas to develop a project to generate addresses of other currencies?

**Comment by Equim-chan** [comment]
For example?

**Comment by ORGaniZMo** [comment]
maybe GRAFT Network https://github.com/graft-project/GraftNetwork

**Comment by lubhub612** [comment]
can we use other coins innstead of moreno?I tried it but fail miserably....  suggestions needed

**Comment by Equim-chan** [comment]
It seems I can just add the network byte of GRAFT to it. According to its source it should be 90? https://github.com/graft-project/GraftNetwork/blob/51f4cbc05f7efb4cd2141b86931fc568d35c59e4/src/cryptonote_config.h#L166

**Comment by Equim-chan** [comment]
I'm not sure if it works, I may try it first.

**Comment by Equim-chan** [comment]
@lubhub612 @ORGaniZMo Can you try the latest version?

https://github.com/monero-ecosystem/vanity-monero/releases/tag/v0.2.8

**Comment by ORGaniZMo** [comment]
> Can you try the latest version?

Work for me, thx
